platform :ios, '10.0'

target 'Genome' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

    pod 'FlybitsV3KernelSDK', '1.0.0-53'
    pod 'FlybitsV3ContextSDK', '1.0.0-53'
    pod 'FlybitsV3PushSDK', '1.0.0-53'
    pod 'DMSwipeCards'

end
